'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { useWorkout, type Exercise } from '@/hooks/use-workout';

export default function NewWorkoutPage() {
  const router = useRouter();
  const { startWorkout } = useWorkout();
  const [workoutName, setWorkoutName] = useState('');
  const [selectedTemplate, setSelectedTemplate] = useState<string | null>(null);
  const [isCreating, setIsCreating] = useState(false);
  
  // Common workout templates
  const workoutTemplates = [
    {
      id: 'push',
      name: 'Push Day',
      description: 'Chest, Shoulders, Triceps',
      exercises: ['Bench Press', 'Overhead Press', 'Incline Dumbbell Press', 'Tricep Dips', 'Lateral Raises']
    },
    {
      id: 'pull',
      name: 'Pull Day',
      description: 'Back, Biceps',
      exercises: ['Pull-ups', 'Barbell Rows', 'Lat Pulldowns', 'Bicep Curls', 'Face Pulls']
    },
    {
      id: 'legs',
      name: 'Leg Day',
      description: 'Legs, Glutes',
      exercises: ['Squats', 'Deadlifts', 'Lunges', 'Leg Press', 'Calf Raises']
    },
    {
      id: 'upper',
      name: 'Upper Body',
      description: 'Full Upper Body',
      exercises: ['Bench Press', 'Pull-ups', 'Overhead Press', 'Rows', 'Dips']
    },
    {
      id: 'full',
      name: 'Full Body',
      description: 'Complete Workout',
      exercises: ['Squats', 'Bench Press', 'Deadlifts', 'Pull-ups', 'Overhead Press']
    }
  ];

  const createWorkout = async () => {
    setIsCreating(true);
    try {
      const template = selectedTemplate && selectedTemplate !== 'empty' 
        ? workoutTemplates.find(t => t.id === selectedTemplate) 
        : null;

      // Auto-generate workout name with format "Entrenamiento YYYY-MM-DD HH:mm"
      const now = new Date();
      const autoGeneratedName = workoutName.trim() || 
        `Entrenamiento ${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}-${String(now.getDate()).padStart(2, '0')} ${String(now.getHours()).padStart(2, '0')}:${String(now.getMinutes()).padStart(2, '0')}`;

      // Convert template exercises to Exercise objects
      const exercises: Exercise[] = template ? template.exercises.map((exerciseName, index) => ({
        id: `exercise-${Date.now()}-${index}`,
        name: exerciseName,
        sets: [],
        restTime: 60
      })) : [];

      // Start workout using the hook (localStorage) and wait for it to complete
      const workout = await startWorkout({
        name: autoGeneratedName,
        exercises
      });

      // Only navigate after workout is created and state is updated
      if (workout) {
        router.push(`/workout/active`);
      }
    } catch (error) {
      console.error('Error creating workout:', error);
      alert('Error al crear el entrenamiento. Por favor, intenta de nuevo.');
    } finally {
      setIsCreating(false);
    }
  };

  const createEmptyWorkout = () => {
    setSelectedTemplate(null);
    createWorkout();
  };

  return (
    <div className="flex-1 p-4">
      <div className="max-w-md mx-auto space-y-6">
        {/* Header */}
        <div className="flex items-center gap-3">
          <Button
            variant="ghost"
            size="sm"
            onClick={() => router.back()}
            className="text-gray-400 hover:text-white p-2"
          >
            <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" />
            </svg>
          </Button>
          <h1 className="text-2xl font-bold text-white">New Workout</h1>
        </div>

        {/* Workout Name */}
        <Card className="bg-black border-neutral-800">
          <CardHeader>
            <CardTitle className="text-lg text-white">Workout Name (Optional)</CardTitle>
            <p className="text-sm text-neutral-500">Leave empty to auto-generate name</p>
          </CardHeader>
          <CardContent>
            <Input
              type="text"
              placeholder="Ej: Push Day, Entrenamiento Piernas..."
              value={workoutName}
              onChange={(e) => setWorkoutName(e.target.value)}
              className="bg-neutral-900 border-neutral-800 text-white placeholder-neutral-500"
              maxLength={50}
            />
          </CardContent>
        </Card>

        {/* Template Selection */}
        <Card className="bg-black border-neutral-800">
          <CardHeader>
            <CardTitle className="text-lg text-white">Choose Template</CardTitle>
            <p className="text-sm text-neutral-500">Or start with an empty workout</p>
          </CardHeader>
          <CardContent className="space-y-3">
            {workoutTemplates.map((template) => (
              <div
                key={template.id}
                onClick={() => setSelectedTemplate(template.id)}
                className={`p-3 rounded-lg border cursor-pointer transition-all ${
                  selectedTemplate === template.id
                    ? 'border-white bg-neutral-900'
                    : 'border-neutral-800 bg-black hover:border-neutral-600'
                }`}
              >
                <div className="flex items-center justify-between">
                  <div>
                    <h3 className="font-semibold text-white">{template.name}</h3>
                    <p className="text-sm text-neutral-500">{template.description}</p>
                  </div>
                  <div className="flex items-center">
                    <span className="text-xs text-neutral-500 mr-2">
                      {template.exercises.length} exercises
                    </span>
                    {selectedTemplate === template.id && (
                      <div className="w-5 h-5 rounded-full bg-white flex items-center justify-center">
                        <svg className="w-3 h-3 text-black" fill="currentColor" viewBox="0 0 20 20">
                          <path fillRule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clipRule="evenodd" />
                        </svg>
                      </div>
                    )}
                  </div>
                </div>
                {selectedTemplate === template.id && (
                  <div className="mt-3 pt-3 border-t border-neutral-800">
                    <div className="flex flex-wrap gap-1">
                      {template.exercises.map((exercise) => (
                        <span
                          key={exercise}
                          className="text-xs bg-neutral-900 text-neutral-300 px-2 py-1 rounded border border-neutral-800"
                        >
                          {exercise}
                        </span>
                      ))}
                    </div>
                  </div>
                )}
              </div>
            ))}

            {/* Empty Workout Option */}
            <div
              onClick={() => setSelectedTemplate('empty')}
              className={`p-3 rounded-lg border cursor-pointer transition-all ${
                selectedTemplate === 'empty'
                  ? 'border-white bg-neutral-900'
                  : 'border-neutral-800 bg-black hover:border-neutral-600'
              }`}
            >
              <div className="flex items-center justify-between">
                <div>
                  <h3 className="font-semibold text-white">Empty Workout</h3>
                  <p className="text-sm text-neutral-500">Start from scratch</p>
                </div>
                {selectedTemplate === 'empty' && (
                  <div className="w-5 h-5 rounded-full bg-white flex items-center justify-center">
                    <svg className="w-3 h-3 text-black" fill="currentColor" viewBox="0 0 20 20">
                      <path fillRule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clipRule="evenodd" />
                    </svg>
                  </div>
                )}
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Create Button */}
        <div className="space-y-3">
          <Button
            onClick={() => selectedTemplate === 'empty' ? createEmptyWorkout() : createWorkout()}
            disabled={!selectedTemplate || isCreating}
            className="w-full h-12 bg-white hover:bg-neutral-200 text-black text-lg disabled:opacity-50 disabled:cursor-not-allowed font-semibold"
          >
            {isCreating ? (
              <div className="flex items-center gap-2">
                <div className="w-4 h-4 border-2 border-black border-t-transparent rounded-full animate-spin"></div>
                Creating...
              </div>
            ) : (
              `Start ${selectedTemplate === 'empty' ? 'Empty' : 'Template'} Workout`
            )}
          </Button>

          <Button
            variant="ghost"
            onClick={() => router.back()}
            className="w-full text-neutral-500 hover:text-white"
          >
            Cancel
          </Button>
        </div>
      </div>
    </div>
  );
}