'use client';

import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { ShimmerButton } from '@/components/magicui/shimmer-button';
import { useWorkout } from '@/hooks/use-workout';
import type { Exercise } from '@/types';
import { ArrowLeft, ChevronRight, Loader2 } from 'lucide-react';

export default function NewWorkoutPage() {
  const router = useRouter();
  const { startWorkout } = useWorkout();
  const [loadingId, setLoadingId] = useState<string | null>(null);

  // Common workout templates
  const workoutTemplates = [
    {
      id: 'push',
      name: 'Push Day',
      description: 'Chest, Shoulders, Triceps',
      exercises: ['Bench Press', 'Overhead Press', 'Incline Dumbbell Press', 'Tricep Dips', 'Lateral Raises']
    },
    {
      id: 'pull',
      name: 'Pull Day',
      description: 'Back, Biceps',
      exercises: ['Pull-ups', 'Barbell Rows', 'Lat Pulldowns', 'Bicep Curls', 'Face Pulls']
    },
    {
      id: 'legs',
      name: 'Leg Day',
      description: 'Legs, Glutes',
      exercises: ['Squats', 'Deadlifts', 'Lunges', 'Leg Press', 'Calf Raises']
    },
    {
      id: 'upper',
      name: 'Upper Body',
      description: 'Full Upper Body',
      exercises: ['Bench Press', 'Pull-ups', 'Overhead Press', 'Rows', 'Dips']
    },
    {
      id: 'full',
      name: 'Full Body',
      description: 'Complete Workout',
      exercises: ['Squats', 'Bench Press', 'Deadlifts', 'Pull-ups', 'Overhead Press']
    }
  ];

  const handleStartWorkout = async (templateId: string | null) => {
    setLoadingId(templateId || 'quick-start');
    try {
      const template = templateId
        ? workoutTemplates.find(t => t.id === templateId)
        : null;

      // Auto-generate workout name with format "Entrenamiento YYYY-MM-DD HH:mm"
      const now = new Date();
      const autoGeneratedName = `Entrenamiento ${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}-${String(now.getDate()).padStart(2, '0')} ${String(now.getHours()).padStart(2, '0')}:${String(now.getMinutes()).padStart(2, '0')}`;

      // Convert template exercises to Exercise objects using the same timestamp
      const exercises: Exercise[] = template ? template.exercises.map((exerciseName, index) => ({
        id: `exercise-${Date.now()}-${index}`,
        sessionId: '', // se completará cuando startWorkout asigne la sesión
        name: exerciseName,
        sets: [],
        restTime: 60,
        order: index,
        createdAt: now.toISOString(),
        updatedAt: now.toISOString(),
      })) : [];

      // Start workout using the hook (localStorage) and wait for it to complete
      const workout = await startWorkout({
        name: autoGeneratedName,
        exercises
      });

      // Only navigate after workout is created and state is updated
      if (workout) {
        router.push(`/workout/active`);
      }
    } catch (error) {
      console.error('Error creating workout:', error);
      alert('Error al crear el entrenamiento. Por favor, intenta de nuevo.');
      setLoadingId(null);
    }
  };

  return (
    <div className="min-h-screen bg-black text-white p-6 flex flex-col">
      <div className="max-w-md mx-auto w-full space-y-8">
        {/* Header */}
        <div className="flex items-center gap-4 pt-2">
          <button
            onClick={() => router.back()}
            className="text-neutral-400 hover:text-white transition-colors"
            aria-label="Go back"
          >
            <ArrowLeft className="w-6 h-6" />
          </button>
          <h1 className="text-xl font-semibold tracking-tight">New Workout</h1>
        </div>

        {/* Quick Start Section */}
        <div className="space-y-4">
          <div onClick={() => handleStartWorkout(null)}>
             <ShimmerButton className="w-full shadow-2xl py-4">
                <span className="text-center text-base font-medium tracking-tight text-white whitespace-pre-wrap dark:from-white dark:to-slate-900/10">
                  {loadingId === 'quick-start' ? (
                    <div className="flex items-center gap-2">
                      <Loader2 className="w-4 h-4 animate-spin" />
                      Starting...
                    </div>
                  ) : (
                    "Quick Start"
                  )}
                </span>
             </ShimmerButton>
          </div>
          <p className="text-xs text-neutral-500 text-center">
            Starts an empty workout immediately
          </p>
        </div>

        {/* Routines List */}
        <div className="space-y-4 pt-4">
          <h2 className="text-sm font-medium text-neutral-400 uppercase tracking-wider px-1">
            Routines
          </h2>
          
          <div className="space-y-1">
            {workoutTemplates.map((template) => (
              <button
                key={template.id}
                onClick={() => handleStartWorkout(template.id)}
                disabled={loadingId !== null}
                className="w-full group flex items-center justify-between p-4 rounded-lg hover:bg-neutral-900 transition-all border border-transparent hover:border-neutral-800 text-left"
              >
                <div className="space-y-1">
                  <h3 className="font-medium text-white group-hover:text-white/90 transition-colors">
                    {template.name}
                  </h3>
                  <p className="text-xs text-neutral-500">
                    {template.description} • {template.exercises.length} exercises
                  </p>
                </div>
                
                <div className="text-neutral-600 group-hover:text-white transition-colors">
                  {loadingId === template.id ? (
                    <Loader2 className="w-5 h-5 animate-spin" />
                  ) : (
                    <ChevronRight className="w-5 h-5" />
                  )}
                </div>
              </button>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}